run:
  timeout: 5m
  tests: true
  go: '1.22'

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - errorlint
    - copyloopvar
    - gci
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unused

linters-settings:
  stylecheck:
    checks: [ "all", "-ST1003" ]
  gocyclo:
    min-complexity: 15
  govet:
    disable:
      - loopclosure
  gosec:
    excludes: [ "G108", "G115" ]
    exclude-generated: true
    confidence: medium
  revive:
    rules:
      - name: redefines-builtin-id
        disabled: true
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  dogsled:
    max-blank-identifiers: 6
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: false
  gosimple:
    checks: [ "all" ]
  staticcheck:
    checks: [ "all", "-SA1019" ]
  gci:
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/pundiai/go-sdk)
  errcheck:
    check-type-assertions: false
    check-blank: false
