scrape_configs:
  - job_name: "node"
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ "host.docker.internal:26660" ]
        labels:
          name: "local"