name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - '*/go.mod'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - '*/go.mod'

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run make test
        run: make test
